# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose the port FastAPI will run on
EXPOSE 10000

# Start FastAPI app
CMD ["uvicorn", "main_main:app", "--host", "0.0.0.0", "--port", "10000"]