# Use compatible Python version for TensorFlow
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Install system packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY api/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy all project files
COPY . .

# Move into api directory to run FastAPI app
WORKDIR /app/api

# Expose port
EXPOSE 8000

# Run the API server
CMD ["uvicorn", "main_main:app", "--host", "0.0.0.0", "--port", "8000"]
