services:
  - type: web
    name: agri-fasal-api
    env: docker
    plan: free
    repo: https://github.com/Nemil-devloper/AGRI-FASAL-MITRA
    branch: main
    rootDir: Fasal-Mitra/DeepLearningproject  # 👈 this is required
    dockerfilePath: Dockerfile
